Repository wzxcs/custom-hooks, pull requests merged in 2022-10, with the labels that each got.

#1 [added]: useState Hook
  React Hooks/Date.js
  React Hooks/useState.js
Labels: good first issue, hacktoberfest-accepted

#2 [added] UseEffectHook Example
  React Hooks/useEffect.js
Labels: enhancement, good first issue, hacktoberfest-accepted

#3 [added] useContext.js example
  React Hooks/useContext.js
Labels: enhancement, good first issue, hacktoberfest-accepted

#4 used context example by converting and managing multiple hooks
  React Hooks/useContext.js
Labels: enhancement, good first issue, hacktoberfest-accepted

#5 Create useRef.js -- helps in reducing the render count
  React Hooks/useRef.js
Labels: enhancement, good first issue, hacktoberfest-accepted

#6 Create useRerender.js
  React Hooks/useRerender.js
Labels: hacktoberfest-accepted
